# settings.yml
project: keypad_backlight
name: KeypadBacklight
version: 0.0.1
settings:
  - name: MqttId
    type: int
    default: 0
    key: l_mqtt_id
  - name: Ip
    type: std::string
    default: 192.168.0.111
    key: mq_ip
  - name: Port
    type: int
    default: 8081
    key: mq_port
  - name: PulseTime
    type: int
    default: 4
    key: t_pulse
    min: 1
    max: 10