# settings.yml
project: tressure
name: TressureBox
version: 0.0.1
settings:
  - name: PulseDuration
    type: int
    default: 100
    key: f_pulse
  - name: BoostDelay
    type: int
    default: 100
    key: f_boost
  - name: MqttId
    type: int
    default: 0
    key: l_mqtt_id
  - name: BatteryMax
    type: int
    default: 3150
    key: b_max
  - name: BatteryMin
    type: int
    default: 2315
    key: b_min
  - name: Ip
    type: std::string
    default: 192.168.0.111
    key: mq_ip
  - name: Port
    type: int
    default: 8081
    key: mq_port
  - name: LedRed
    type: int
    default: 30
    key: led_red
  - name: LedGreen
    type: int
    default: 30
    key: led_green
  - name: LedBlue
    type: int
    default: 30
    key: led_blue