# settings.yml
project: dmx_light
name: DmxLight
version: 0.0.1
settings:
  - name: MqttId
    type: int
    default: 0
    key: l_mqtt_id
  - name: Ip
    type: std::string
    default: 192.168.0.111
    key: mq_ip
  - name: Port
    type: int
    default: 8081
    key: mq_port