# settings.yml
project: cipher_box
name: CipherBox
version: 0.0.1
settings:
  - name: Url
    type: std::string
    default: "http://192.168.0.111:8080"
    key: http_url
  - name: DeltaError
    type: int
    default: 15
    key: adc_error
    min: 0
    max: 100
  - name: BounceTimeMs
    type: int
    default: 500
    key: adc_bounce
    min: 0
    max: 10000