# settings.yml
project: relay
name: RelayController
version: 0.0.1
settings:
  - name: HttpUrl
    type: std::string
    default: https://192.168.1.50/mini_games/lights/lights.json
    key: h_url
  - name: HttpDelay
    type: int
    default: 300
    key: h_delay